@startuml

Package  "Modele" <<Frame>> #A4A4A4 {
    class PartieModele {
    - tourActuel : int
    - pileCarte : PileCarteModele
    - plateau : PlateauModele
    - joueurEnAction : ProfModele
    + creationPersoObjM() : void
    + getPileCarte() : PileCarteModele
    + getPlateau() : PlateauModele
    + getJoueurEnAction() : ProfModele
    + setJoueurEnAction(ProfModele joueurEnAction) : void
    }
    class PlateauModele {
    - nbTuile : int
    }
    class TuileModele {
    - nbCase : int
    - id : int
    - tuileAccessible : Tuile []
    + tuileContainProf() : boolean
    + tuileContainEtu() : boolean
    + rangementEtudiants() : void
    + porteSurTuile() : void
    + setPersOnTuile() : void
    + getId() : int
    + setId() : int
    + getTuileAccessible() : TuileModele []
    + setTuileAccessible() : void
    + getPorteFermer() : ArrayList<CaseModele>
    }
    class CaseModele {
    - maTuileModele : Tuile
    - passable : boolean
    - coordX : int
    - coordY : int
    + containDoorLocked() : boolean
    + nombreEtu() : int
    + getPassable() : boolean
    + setPassable(boolean passable)
    + getCoordX() : int
    + getCoordY() : int
    + setCoordX(int coordX)
    + setCoordY(int coordY)
    + getMaTuile() : TuileModele
    + setMaTuile(TuileModele maTuile) : void
    }
    abstract class ElemCaseModele {
    - image : Image
    - MaCase : CaseModele
    + getImage() : Image
    + setImage(Image image) : void
    + getMaCase() : CaseModele
    + setMaCase(CaseModele maCase) : void
    }
    class MurModele{}
    class PorteModele {
    - verrouiller : boolean
    + isVerrouiller() : boolean
    + setVerrouiller() : void
    }
    class ObjectifModele {
    - activer : boolean
    - expRapporte : int
    + setActiver() : void
    + isActiver() : boolean
    + getExpRapporte() : int
    }
    class MachineCafeModele {
    + spawnDebutManche(PileCarteModele pile,int exptot)
    }
    abstract class PersonnageModele {
    - nbPa : int
    - pv : int
    - pa :int
    - nom : String
    - jouable : boolean
    + getPv() : int
    + setPv(int pv) : void
    + getPa() : int
    + setPa(int pa) : void
    + getNom() : String
    + setNom(String nom) : void
    + getJouable() : boolean
    + setJouable(boolean jouable) : void
    + getNbPa()
    + tourDeJeu()
    'Attaque'
    + deplacement() : void
    + reinitPa () : void
    + passer() : void
    + isValider() : boolean
    + setJouable(boolean jouable) : void
    }
    class ProfModele {
     - exp : int
     - inventaire : InventaireModele
     - info : BufferedImage
     + choixOutilEtZone() : void
     + valider(ArrayList<PersonnageModele> per,int indexObjet) : void
     + fouiller(PileCarteModele p) : void
     + choixPorte() : void
     + ouvriPorte(PorteModele porte) : boolean
     + choixModifInventaire() : void
     + modifInventaire(int indexDépart,int indexArriv) : void
     + activerObjectif() : void
     + deplacement() : void
     + capaciteActive() : void
     + capacitePassive() : void
     + getExp() : int
     + setExp(int exp) : void
     + getInventaire() : InventaireModele
     + setImage(BufferedImage img) : void
     + getInfo() : BufferedImage
    }
    class EtudiantModele {
    - nbDemandeValidation : int
    - typeUV : String []
    - expRapporte : int
    + valider(ArrayList<PersonnageModele> per) : void
    + deplacement() : void
    + tourDeJeu() : void
    + getNbDemandeValidation() : int
    + setNbDemandeValidation(int nbDemandeValidation) : void
    + getTypeUV() : String[]
    + getExpRapporte() : int
    }
    interface SpecialiteModele {
        + capaciteActive() : void
        + capacitePassive() : void
    }
    class InventaireModele {
    - capacite : int
    - nbObjetActuel : int
    + getContenuInventaire() : ArrayList<ObjetModele>
    + suppressionObjet(int index) : void
    }
    class ObjetModele {
    - nom : String
    - emplacement : int
    + getNom() : String
    }
    class CleModele{}
    class OutilValidationModele {
    - portee : int
    - nbUVVal : int
    - nbActivation : int
    - nbTentative : int
    - tauxDeReussite : int
    - typeUV : String []
    + getModifier() : boolean
    + setModifier() : void
    + getNbActivation() : int
    + setNbActivation(int nbActivation) : void
    + getNbTentative() : int
    + setNbActivation(int nbTentative) : void
    + getPortee() : int
    + setPortee(int portee) : void
    + getNbUVVal() : int
    + getTypeUV() : String[]
    + getTauxDeReussite() : int
    + setTauxDeReussite(int taux) : void
    }
    abstract class CarteModele {
    - Intitule : String
    - img : BufferedImage
    - imgI : ImageIcon
    + getIntitule() : String
    + getImg() : BufferedImage
    + getImgIcon() : ImageIcon
    }
    class CarteEtudianteModele {
    - malchance : int
    + apparition(CaseModele c,int exp) : void
    }
    class PileCarteModele {
    - nbCarte : int
    - listeCarte : ArrayList<CarteModele>
    + remplissage() : void
    + getNbCarte() : int
    + setNbCarte(int nbCarte)
    + getListeCarte() : ArrayList<CarteModele>
    + setListeCarte() : void
    }
    class ProfPhysiqueModele{
    + capaciteActive() : void
    + capacitePassive() : void
    }
    class ProfHumaModele{
    + capaciteActive() : void
    + capacitePassive() : void
    }
    class ProfMathModele {
    + capaciteActive() : void
    + capacitePassive() : void
    }
    class ProfInfoModele{
    + capaciteActive() : void
    + capacitePassive() : void
    }
    class SolModele{

    }
    class SortieModele{

    }
}
'Relation
PartieModele "1" *-- "1-*" PersonnageModele
PartieModele "1" *-- "1-*" ObjectifModele
PartieModele "1" *-- "1-*" MachineCafeModele
PartieModele "1" -- "1" PileCarteModele
PartieModele "1" -- "1" PlateauModele
PartieModele "1" -- "1" ProfModele
PlateauModele "1" *-- "1-*" TuileModele
TuileModele "1" *-- "1-*" CaseModele
CaseModele "1" o-- "0-*" ElemCaseModele
ElemCaseModele <|-- MurModele
ElemCaseModele <|-- ObjectifModele
ElemCaseModele <|-- MachineCafeModele
ElemCaseModele <|-- PersonnageModele
TuileModele "1" o-- "0-*" PersonnageModele
MurModele <|-- PorteModele
PersonnageModele <|-- EtudiantModele
PersonnageModele <|-- ProfModele
ProfModele "1" -- "1" InventaireModele
ProfPhysiqueModele --|> ProfModele
ProfHumaModele --|> ProfModele
ProfInfoModele --|> ProfModele
ProfMathModele --|> ProfModele
ProfModele ..|> SpecialiteModele
InventaireModele o-- ObjetModele
ObjetModele <|-- CleModele
ObjetModele <|-- OutilValidationModele
CarteModele <|-- ObjetModele
CarteModele <|-- CarteEtudianteModele
PileCarteModele "1" *-- "0-*" CarteModele
SolModele --|> ElemCaseModele
SortieModele --|> ElemCaseModele
@enduml