@startuml
actor Prof #blue
entity Inventaire
entity Plateau
actor Etudiant #red

== Deroulement d'un tour de jeu ==

alt si pas d'etudiant sur tuile
    Prof --[#blue]> Plateau : Mouvement
end
alt si carte étudiante
    Prof --[#blue]> Etudiant : Fouiller
    Etudiant -[#red]> Plateau : Apparait
else sinon
    Prof --[#blue]> Inventaire : Fouiller
end
alt si cle equipe
    Prof --[#blue]> Plateau : Ouvrir porte
end
Prof --[#blue]> Inventaire : Modifier inventaire
alt si objectif sur tuile
    Prof --[#blue]> Plateau : Activer objectif
end
alt si etudiant sur tuile a portee
    Prof --[#blue]> Etudiant : ValiderUV
end
alt si pas de prof sur tuile
    Etudiant -[#red]> Plateau : Mouvement
end
alt si prof sur tuile
    Etudiant -[#red]> Prof : DemandeValidationUV
end
Etudiant -[#red]> Plateau : Apparait
@enduml