@startuml

Package "Vue" <<Frame>> #D8D8D8 {
    class MenuFen {
      - mPanel : MenuPanel
      + launch()
    }
    class MenuPanel{
      - b1 : MenuJButton
      - b2 : MenuJButton
      - b3 : MenuJButton
      + addListener() : void
      + paintComponent() : void
    }
    class MenuJButton{
      - imageNonSelect : Image
      - imageSelect  : Image
    }
    class GameFen{
      - mPartie : PartieModele
      - gamePane : GamePane
      + repaintInfo() : void
    }
    class GamePane {
      - gamePanelInfo : GamePanelInfo
      - plateau : PlateauPanel
      - mpartie : PartieModele
      - gbp : GameButtonpane
      + initAttribut() : void
    }
    class GamePanelInfo{
      - p : ProfModele
      + setJoueur() : void
      + paintComponent() : void
    }
    class GameButtonPane{
      - validation : GameButton
      - fouiller : GameButton
      - deplacer : GameButton
      - ouvPorte : GameButton
      - modifInv : GameButton
      - actObj : GameButton
      - capAct : GameButton
      - capPas : GameButton
      - passer : GameButton
      + addListeners() : void
    }
    class GameButton{
      - actionJoueur : int
    }

    class PlateauPanel{
      - plateau : PlateauModele
      - map : char[][]
      - cases : CaseModele[][]
      + affichageMapConsole() : void
      + parcoursMap() : char[][]
      + listeTuile() : ArrayList<TuileModele>
      + updateListeTuile() : void
      + map() : CaseModele[][]
      + afficheMapGraphique() : void
      + paintComponent() : void
    }
}
MenuFen "1" -- "1" MenuPanel
MenuPanel "1" -- "3" MenuJButton
GameFen "1" -- "1" GamePane
GamePane "1" -- "1" PlateauPanel
GamePane "1" -- "1" GamePanelInfo
GamePane "1" -- "1" GameButtonPane
GameButtonPane "1" -- "9" GameButton

@enduml